server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: DEMO-SERVICE
          uri: http://localhost:9090
          predicates:
            - Path=/api/**
    loadbalancer:
    ribbon:
      enabled: false