spring:
  datasource:
    url: none
    username: none
    password: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
    liquibase-schema: pet_liquibase
  application:
    name: pet
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8082